#!/Users/user/PythonProjects/Numerolog_free/.venv/bin/python3.13
from clients_info import get_client_info
from fate_matrix import get_matrix_pdf


def main():
    client_info = get_client_info()
    # coordinates = get_coords()
    file_name = get_matrix_pdf(client_info)
    print(f'Изучай {client_info} матрицу настоящим образом')


if __name__ == '__main__':
    main()
