#!/Users/user/PythonProjects/Numerolog_free/.venv/bin/python3.13
from loguru import logger
from pathlib import Path
import os

from config.settings import TEMPLATES_PATH, PDF_PATH

from business_logic.arcanes_classes import Client, Star

from input_module.clients_info import get_client_info
from data_requests.data_for_images import get_star_content
from data_requests.data_for_text import get_star_analytic
from reports.pdf_creator import create_star_report


# Основная функция программы
@logger.catch
def main():
    """
    Главная функция программы. Выполняет следующие шаги:
    1. Получение данных клиента.
    2. Создание арканов для звезды по данным клиента.
    3. Подготовка данных для создания страницы звезда.
    4. Подготовка данных для создания страниц аналитики звезды.
    5. Создание отчета в виде pdf файла.
    """
    # Настройка логгера
    # configure_logger()

    # 1. Получение данных клиента
    logger.info("Получение данных клиента...")
    client_info = get_client_info()
    logger.debug(f'Имя и ДР клиента {client_info}')

    # Создание контекста для шаблонов страниц
    logger.info("Создание контента страниц...")

    # 2. Создание арканов для звезды (star) по данным клиента.
    logger.info("Создание контента страницы star")
    client_star = Star(client_info)
    logger.debug(f'{client_star}')

    # 3. Подготовка данных для создания страницы звезда.
    page_star_content = get_star_content(star=client_star)
    logger.debug(f'{page_star_content}')

    # 4. Подготовка данных для создания страниц аналитики звезды.
    logger.info("Создание аналитики звезды...")
    page_star_analytic = get_star_analytic(star=client_star)
    logger.debug(f'{page_star_analytic}')
    logger.info("Аналитика звезды создана")

    # 5. Создание отчета в виде pdf файла.
    result = create_star_report(
        page_content=page_star_content,
        analytic_content=page_star_analytic
    )

    if not result:
        logger.error('Не удалось сформировать заполненную html страницу star')

    logger.info("Завершение создания страницы star")
    # Завершение создания страницы star

    # Завершение работы программы
    logger.info("Программа успешно завершила работу.")


# Точка входа в программу
if __name__ == "__main__":
    from utils.log_utils import configure_logger
    configure_logger()
    main()
